[arq]
192.168.56.109

[db]
192.168.56.134

[app]
192.168.56.194

[cli]
# O IP será atribuído dinamicamente pelo DHCP, verifique após o provisionamento do arq
192.168.56.50

[servidores:children]
arq
db
app
cli
