---
- name: Configuração Comum a todas as máquinas
  hosts: servidores
  become: yes
  tasks:
    - name: Atualizar sistema
      apt:
        update_cache: yes
        upgrade: yes

    - name: Instalar Chrony e NFS Client
      apt:
        name: [chrony, nfs-common]
        state: present

    - name: Configurar fuso horário
      timezone:
        name: America/Recife

    - name: Criar grupo ifpb
      group:
        name: ifpb
        state: present

    - name: Criar usuários da equipe
      user:
        name: "{{ item }}"
        groups: ifpb
        shell: /bin/bash
      loop: ["jesse", "joao"]

    - name: Hardening SSH e Mensagem de Saudação
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^AllowGroups', line: 'AllowGroups vagrant ifpb' }
      notify: restart ssh

    - name: Configurar MOTD
      copy:
        content: "Acesso apenas para pessoas com autorização expressa!!!"
        dest: /etc/motd

    - name: Permitir sudo sem senha para grupo ifpb
      lineinfile:
        path: /etc/sudoers
        line: "%ifpb ALL=(ALL) NOPASSWD:ALL"
        state: present

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted