---
- name: Configuração do Servidor de Arquivos (arq)
  hosts: arq
  become: yes
  tasks:
    - name: Configurar LVM nos 3 discos extras
      lvg:
        vg: dados
        pvs: /dev/sdb,/dev/sdc,/dev/sdd
    - lvol:
        vg: dados
        lv: ifpb
        size: 15G
    - filesystem:
        fstype: ext4
        dev: /dev/dados/ifpb
    - mount:
        path: /dados
        src: /dev/dados/ifpb
        fstype: ext4
        state: mounted

    - name: Configurar NFS
      apt: name=nfs-kernel-server state=present
    - file: path=/dados/nfs state=directory mode='0777'
    - lineinfile:
        path: /etc/exports
        line: "/dados/nfs 192.168.56.0/24(rw,sync,all_squash,anonuid=1001,anongid=1001)" # Adaptado do projeto
      notify: reload nfs

    # Adicionar aqui tasks para DHCP (isc-dhcp-server) e DNS (bind9) conforme práticas 5 e 6

  handlers:
    - name: reload nfs
      service: name=nfs-kernel-server state=reloaded