option domain-name "jesse.joao.devops";
option domain-name-servers 192.168.56.109;

default-lease-time 180;
max-lease-time 3600;

ddns-update-style none;
authoritative;

subnet 192.168.56.0 netmask 255.255.255.0 {
  range 192.168.56.50 192.168.56.100;
  option routers 192.168.56.1;
  
  # Reserva para servidor db
  host db {
    hardware ethernet 08:00:27:3A:00:01;
    fixed-address 192.168.56.134;
  }
  
  # Reserva para servidor app
  host app {
    hardware ethernet 08:00:27:3A:00:02;
    fixed-address 192.168.56.194;
  }
}
